# Generated by Django 4.0.3 on 2022-03-24 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_poll_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
